version: '3'


services:
  app:
    build: .
    command: python app.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - ${PIXOO_REST_PORT:-5000}:5000
    environment:
      - PIXOO_DEBUG=${PIXOO_DEBUG:-false}
      - PIXOO_REST_DEBUG=${PIXOO_REST_DEBUG:-false}
      #
      - PIXOO_HOST=${PIXOO_HOST:-pixoo}
      - PIXOO_SCREEN_SIZE=${PIXOO_SCREEN_SIZE:-64}
    restart: unless-stopped
